version: "3"
services:
  postgres:
    env_file:
      - .env
    image: postgres:11.4
    container_name: postgres
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  app:
    env_file:
      - .env
    build: .
    container_name: app
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    ports:
      - 5000:5000
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
